#!/bin/bash


# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

# Script to backup all MySQL databases and compress the backup file.
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql