#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then 
        echo "Hi"
        ((count++))
    else

        echo "Best School"
        ((count++))
    fi
done
